In [1]:
# Numpy での 行列の積

import numpy as np
w = np.array([[1,2,3],[4,5,6]])
x = np.array([[1],[2],[3]])
w.dot(x)

array([[14],
       [32]])

In [2]:
# TensorFlowでの行列の積

import tensorflow as tf
import numpy as np

# numpy 配列
w_data = np.array([[1,2,3],[4,5,6]]).astype("int32")
x_data = np.array([[1],[2],[3]]).astype("int32")

# 行列定義
w = tf.get_variable("weight" ,initializer=tf.constant(w_data))
x = tf.get_variable("x" ,initializer=tf.constant(x_data))
f = tf.matmul(w, x)

# TesnsorFlow 初期化
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

# 行列の積の実行
sess.run(f) 

array([[14],
       [32]], dtype=int32)

In [10]:
# 対角線行列 diagonal tensor 
# https://www.tensorflow.org/api_docs/python/tf/diag
#
import tensorflow as tf
import numpy as np

x_array = np.array([1,2,3,4,5]).astype("float32")
x_tf = tf.constant(x_array)

# TesnsorFlow 初期化
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

# 対角線行列 
diag = sess.run(tf.diag(x_tf))
print diag

[[ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  5.]]


In [11]:
sess.run(tf.diag_part(diag))

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)